/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pin_Output_LEFT.h"
#include "Pin_Output_LEFT_aliases.h"
#include "Pin_Input_LEFT.h"
#include "Pin_Input_LEFT_aliases.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "FanController.h"
#include "Pin_Output_DOWN.h"
#include "Pin_Output_DOWN_aliases.h"
#include "Pin_Input_RIGHT.h"
#include "Pin_Input_RIGHT_aliases.h"
#include "Pin_Output_RIGHT.h"
#include "Pin_Output_RIGHT_aliases.h"
#include "Pin_Input_DOWN.h"
#include "Pin_Input_DOWN_aliases.h"
#include "Pin_Output_UP.h"
#include "Pin_Output_UP_aliases.h"
#include "Pin_Input_UP.h"
#include "Pin_Input_UP_aliases.h"
#include "Pin_Input_BallTrigger.h"
#include "Pin_Input_BallTrigger_aliases.h"
#include "ISR_Ball_Trigger.h"
#include "Pin_Serve.h"
#include "Pin_Serve_aliases.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "FanController_DataSend.h"
#include "FanController_PID_ISR.h"
#include "FanController_FW_PWM4.h"
#include "FanController_FW_PWM2.h"
#include "FanController_FW_PWM3.h"
#include "FanController_FW_PWM1.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

