/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "FanController.h"
#include "Pin_Input_LEFT_aliases.h"
#include "Pin_Input_LEFT.h"
#include "Pin_Output_LEFT_aliases.h"
#include "Pin_Output_LEFT.h"
#include "Pin_Input_RIGHT_aliases.h"
#include "Pin_Input_RIGHT.h"
#include "Pin_Input_UP_aliases.h"
#include "Pin_Input_UP.h"
#include "Pin_Input_DOWN_aliases.h"
#include "Pin_Input_DOWN.h"
#include "Pin_Output_RIGHT_aliases.h"
#include "Pin_Output_RIGHT.h"
#include "Pin_Output_UP_aliases.h"
#include "Pin_Output_UP.h"
#include "Pin_Output_DOWN_aliases.h"
#include "Pin_Output_DOWN.h"
#include "UART.h"
#include "FanController_PID_ISR.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

